# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '18.14.2'
  displayName: 'Install Node.js'

- script: |
    npm install
  displayName: 'npm install@9.5.0'
- task: CmdLine@2
  inputs:
    script: 'docker build -t spendkey-cypress .'
  displayName: 'Build docker'

- task: CmdLine@2
  inputs:
    script: 'npx cypress run --spec ./cypress/e2e/uiTest/login-tests.cy.js'
  displayName: 'run docker compose file'
  continueOnError: true
  condition: succeeded()

- task: PublishTestResults@2
  displayName: 'Publish Test Results '
  inputs:
    testRunner: Junit
    testResultsFiles: '**/results.xml'
    searchFolder: '$(System.DefaultWorkingDirectory)/cypress/reports'
    mergeTestResults: true
    failTaskOnFailedTests: true
- task: PublishBuildArtifacts@1
  inputs: 
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'