# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
  branches:
    include:
    - refs/heads/main
resources:
  repositories:
  - repository: self
    type: git
    ref: refs/heads/main
jobs:
- job: Job_1
  displayName: Agent job 1
  pool:
    vmImage: windows-latest
  steps:
  - checkout: self
    fetchTags: false
  - task: NodeTool@0
    displayName: 'Use Node '
    inputs:
      versionSpec: 14.x
  - task: Npm@1
    displayName: Install Npm Dependencies
    inputs:
      verbose: false

  - task: Npm@1
    displayName: Execute Script
    condition: succeededOrFailed()
    inputs:
      command: custom
      verbose: false
      customCommand: run api-test

  - task: PublishTestResults@2
    displayName: 'Publish Test Results '
    inputs:
      testResultsFiles: '**/results-*.xml'
...


